services:
  db-postgres:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: ${POSTGRES_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRES_DATABASE}
    volumes:
      - ./data/postgres:/bitnami/postgresql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql